version: '3.1'

services:
  odoo:
    image: odoo:17.0
    ports:
      - "8069:8069"
    volumes:
      - odoo_data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    depends_on:
      - db
    networks:
      - odoo_network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - odoo_network

networks:
  odoo_network:

volumes:
  odoo_data:
  postgres_data:
