version: '3.1'
services:
  web:
    image: odoo:${ODOO_VERSION:?error}
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      # --- ODOO CONFIG ---
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      # --- ODOO ADDONS ---
      - ./modules:/mnt/extra-addons
      # --- ODOO DATA ---
      - odoo:/var/lib/odoo

    networks:
      - odoo_net

  db:
    image: postgres:${POSTGRES_VERSION:?error}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql
    networks:
      - odoo_net
  
networks:
   odoo_net:
      driver: bridge

volumes:
  odoo:
  db:
